services:

  movies-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      postgresql:
        condition: service_started

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: movies
      PGDATA: /data/postgres
    # volumes:
    #   - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
